### ISSUE TITLE
add TCP conversation & update win transform tracking

### ISSUE THREAD

**Issue by TomasMadeja** [Trace-Share/Trace-Manipulation#1]
tcp_conversation_tracker

- tracks states of tcp conversations (ip-port)
- stores them in conversation dict

- [x] implement tcp_conversation_tracker (preprocess) function

- [x] implement tcp_win (process) function 

- [ ] add tests for tcp_conversation_tracker

- [x] add tests for tcp_win

- [x] add documentation
